### ISSUE TITLE
команды /war /help /team

### ISSUE THREAD

**Issue by secret404** [asyncdargen/evo-plus#10]
Лазя по коду я заметил упоминания команды /war. После чего я попробовал вести её в игре, но такой команды нет. Так вот вопрос : это я не умный что-то не так делаю или это ещё не доработанная функция ?  (тоже история и с /help и /team) Мне было бы со ровно, если я не считал, что эти функции удобные. Заранее спасибо за ответ.

**Comment by ismail0vv** [comment]
броу мне кажется ты просто не с той ветки код посмотрел. Эти команды были в прошлых версиях evoplus. В новой нету таких команд
