### ISSUE TITLE
Баг интерфейса

### ISSUE THREAD

**Issue by Selestor1** [asyncdargen/evo-plus#11]
После достижения нового уровня с интерфейса пропадает вся информация, до перезахода в хаб и обратно
![image](https://github.com/asyncdargen/evo-plus/assets/141501495/1e903aba-a685-4c3c-b95a-6568dcafa6e8)

**Comment by MiKu-YTC** [comment]
![image](https://github.com/asyncdargen/evo-plus/assets/141506437/f4a6865a-165a-4f3d-974a-00c43fd232c1)
При команде /interface Интерфейс пропадает
