### ISSUE TITLE
Таймер боссов

### ISSUE THREAD

**Issue by R2kip** [asyncdargen/evo-plus#13]
Я не знаю у одного у меня такой баг или нет?
![2023-08-17_10 31 43](https://github.com/asyncdargen/evo-plus/assets/56793105/c9e6a142-3eea-466b-85d4-dcbb7458467c)

**Comment by R2kip** [comment]
![2023-08-17_10 34 24](https://github.com/asyncdargen/evo-plus/assets/56793105/181fc965-7b30-4527-88f4-f43c879a99f2)

**Comment by Smole17** [comment]
Исправлено в новой версии.
