### ISSUE TITLE
Совместимость с AdvancedChat

### ISSUE THREAD

**Issue by Qwertyuiop163fex** [asyncdargen/evo-plus#2]
При входе на сервер с EvoPlus и AdvancedChat не работает мод

**Comment by EtoShinya** [comment]
> При входе на сервер с EvoPlus и AdvancedChat не работает мод

Можешь прикрепить полный лог игры?

**Comment by EtoShinya** [comment]
@Qwertyuiop163fex, можешь рассказать, что именно не работает?

**Comment by filipjayfray** [comment]
Перестает работать таймер боссов когда тепаешься на них они просто не записываются.

**Comment by filipjayfray** [comment]
вот лог
[latest.log](https://github.com/asyncdargen/evo-plus/files/11150358/latest.log)

**Comment by filipjayfray** [comment]
и не работает также авто/thx
