### ISSUE TITLE
Новая версия крашит

### ISSUE THREAD

**Issue by edgar06ka** [asyncdargen/evo-plus#22]
https://bytebin.lucko.me/H4gCoeoy3X

**Comment by likeosik** [comment]
Здравствуйте, у меня таже проблема 
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'evo-plus' at 'ru.dargen.evoplus.EvoPlus'!
