### ISSUE TITLE
Краш

### ISSUE THREAD

**Issue by f1owesc** [asyncdargen/evo-plus#4]
Крашится при открытии меню на сервере (в хабе)
Лог
[latest.log](https://github.com/asyncdargen/evo-plus/files/11047133/latest.log)
Скрин модов которые стоят, мб конфликтуют хз
![image](https://user-images.githubusercontent.com/128669905/227107923-a201ecec-d00d-492a-b514-6661f0581477.png)

**Comment by f1owesc** [comment]
крашится так же с оптифабриком, на том же открытии меню

**Comment by EtoShinya** [comment]
> Крашится при открытии меню на сервере (в хабе) Лог [latest.log](https://github.com/asyncdargen/evo-plus/files/11047133/latest.log) Скрин модов которые стоят, мб конфликтуют хз ![image](https://user-images.githubusercontent.com/128669905/227107923-a201ecec-d00d-492a-b514-6661f0581477.png)

Какой версии Java используешь?

**Comment by f1owesc** [comment]
![image](https://user-images.githubusercontent.com/128669905/227239700-c5ae3331-1a97-49b6-b3fc-db1adcba5bad.png)
вот

**Comment by f1owesc** [comment]
другую джаву майн не видет

**Comment by f1owesc** [comment]
лаунчер multimc

**Comment by f1owesc** [comment]
Всё, не крашится
