### ISSUE TITLE
Босс записывается не правильно

### ISSUE THREAD

**Issue by f1owesc** [asyncdargen/evo-plus#5]
Снежный монстр(250) записывается как обычный монстр (110)
![image](https://user-images.githubusercontent.com/128669905/227470986-6a70976c-270b-47d2-8945-11c62cabcae2.png)

**Comment by EtoShinya** [comment]
> Снежный монстр(250) записывается как обычный монстр (110) ![image](https://user-images.githubusercontent.com/128669905/227470986-6a70976c-270b-47d2-8945-11c62cabcae2.png)

Попробуй этот билд.
https://github.com/asyncdargen/evo-plus/releases/tag/1.0.5

**Comment by EtoShinya** [comment]
Исправлено в 1.0.5.
