### ISSUE TITLE
Босс не правильно записывается

### ISSUE THREAD

**Issue by f1owesc** [asyncdargen/evo-plus#6]
гигантская черепаха (220) записывается как гигант (100)
![image](https://user-images.githubusercontent.com/128669905/227704584-16306155-aab3-4533-a556-2bc60fc44991.png)

**Comment by EtoShinya** [comment]
> гигантская черепаха (220) записывается как гигант (100) ![image](https://user-images.githubusercontent.com/128669905/227704584-16306155-aab3-4533-a556-2bc60fc44991.png)

Исправлено в 1.0.5. Перекачай.
